### ISSUE TITLE
uninitialized constant Rails - 

### ISSUE THREAD

**Issue by SerbanC** [corysimmons/jeet-rails#5]
Hi,
I have jeet included in a Compass task for Gulp and when running the task i get this error:

```
NameError on line ["4"] of /Library/Ruby/Gems/2.0.0/gems/jeet-6.1.2/lib/jeet.rb: uninitialized constant Rails
```
Do i need to also have Rails installed?

**Comment by corysimmons** [comment]
I believe so: https://github.com/corysimmons/jeet-rails/blob/master/lib/jeet.rb#L4

**Comment by corysimmons** [comment]
@SerbanC In the meantime, why not check out my newest grid system which is packaged up in a simple stylesheet? https://github.com/corysimmons/lost/blob/master/lost.scss
